# Generated by Django 4.0.4 on 2022-04-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
